"""torch.linalg — Linear algebra operations for mindtorch_v2.

Provides functions aligned with PyTorch's torch.linalg module.
"""

from .linalg import (
    cholesky,
    cond,
    cross,
    det,
    diagonal,
    eig,
    eigh,
    eigvals,
    eigvalsh,
    householder_product,
    inv,
    lstsq,
    lu,
    lu_factor,
    lu_solve,
    matmul,
    matrix_exp,
    matrix_norm,
    matrix_power,
    matrix_rank,
    multi_dot,
    norm,
    pinv,
    qr,
    slogdet,
    solve,
    solve_triangular,
    svd,
    svdvals,
    tensorinv,
    tensorsolve,
    vander,
    vector_norm,
)

__all__ = [
    "cholesky",
    "cond",
    "cross",
    "det",
    "diagonal",
    "eig",
    "eigh",
    "eigvals",
    "eigvalsh",
    "householder_product",
    "inv",
    "lstsq",
    "lu",
    "lu_factor",
    "lu_solve",
    "matmul",
    "matrix_exp",
    "matrix_norm",
    "matrix_power",
    "matrix_rank",
    "multi_dot",
    "norm",
    "pinv",
    "qr",
    "slogdet",
    "solve",
    "solve_triangular",
    "svd",
    "svdvals",
    "tensorinv",
    "tensorsolve",
    "vander",
    "vector_norm",
]
