"""accelerate utils"""
from .modeling import (
    # calculate_maximum_sizes,
    # check_device_map,
    check_tied_parameters_in_config,
    check_tied_parameters_on_same_device,
    compute_module_sizes,
    convert_file_size_to_int,
    dtype_byte_size,
    find_tied_parameters,
    get_balanced_memory,
    get_max_layer_size,
    get_max_memory,
    # get_mixed_precision_context_manager,
    # id_tensor_storage,
    infer_auto_device_map,
    # is_peft_model,
    # load_checkpoint_in_model,
    # load_offloaded_weights,
    # load_state_dict,
    named_module_tensors,
    modify_model_for_pp_infer,
    # retie_parameters,
    # set_module_tensor_to_device,
    # shard_checkpoint,
)
